version: '3'
services:
    summer:
        image: summer
        restart: unless-stopped
        volumes:
            - ./src:/summer
            - ./private:/private
    php:
        image: php:7.3-fpm
        restart: unless-stopped
        volumes:
            - ./html:/html
            - ./private:/private
    web:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "58008:80"
        volumes:
            - ./html:/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
